# .github/workflows/ci.yml

name: Lint and Test CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "**/*.md"
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Lint
        run: make lint

      - name: Run Tests
        run: TEST_MODE=1 make test
